"""
Utility: Tree backend for storing all potential pipelines.
Todo:
Node
    * Some class properties we should add:
        > ID property
        > get_id()

Transformation Tree object
    * Some class methods we should add:
        > print_tree(print_with_ids=false)
        
        adding a list of nodes as children of target...
        > add_nodes (ref to node, [Node] or Node)
        > add_nodes_byname (target_name, [Node] or Node)
        > add_nodes_byid (target_id, [Node] or Node)
        
        adding list of nodes as a path from target...
        > add_paths (ref to node, [Node] or Node)
        > add_paths_byname (target_name, [Node] or Node)
        > add_paths_byid (target_id, [Node] or Node)

        > get_all_nodes_oftype(op_name) # this returns all operators in
        the of specified type
"""
from __future__ import annotations
from anytree import NodeMixin, RenderTree, render
from typing import List, Callable

__authors__ = "Alec Springel"
__version__ = "1.0.0"
__emails__ = "aspring6@uoregon.edu, stal@uoregon.edu"
__credits__ = "Kyra Novitzky, Seth Tal, Ronny Fuentes, Stephanie Schofield"
__date__ = "01/23/2021"


class Node(NodeMixin):
    def __init__(self, function: Callable, parent: Node = None,
                 children: [Node] = None):
        self.name = function.__name__
        self.function = function
        # Parents/children are dynamically generated by checking input/output
        self.parent = parent
        self.id = None
        if children:
            self.children = children

    def set_id(self, id):
        self.id = id

    def set_parent(self, parent):
        self.parent = parent
        return self.parent


class TTree():
    def __init__(self, name: str, root: Node = None):
        self.name = name
        self.root = root
        self.root.set_id(0)
        self.id_iterator = 1

    def set_id(self, node: Node):
        """For use inside of the TTree() class only.
        Sets a node's IDs"""
        node.set_id(self.id_iterator)
        self.id_iterator += 1

    def print(self, id=False):
        """Prints a visual representation of the tree"""
        for pre, fill, node in RenderTree(self.root):
            if(id):
                treestr = u"%s%s (%s)" % (pre, node.name, node.id)
            else:
                treestr = u"%s%s" % (pre, node.name)
            print(treestr.ljust(8))

    def add_path(self, target: Node, path: [Node]):
        """Builds a path starting with target node, and iterating through path,
        inserting these nodes as children of eachother
        (starting with target)"""
        path[0].set_parent(target)
        self.set_id(path[0])
        for i in range(1, len(path)):
            path[i].set_parent(path[i-1])
            self.set_id(path[i])
