"""
CIS 422 Winter 2021
University of Oregon
Bitwise Team
Project One: Time Series Analysis
Utility: Tree backend for storing all potential pipelines.
"""

# import statements below
from anytree import NodeMixin, RenderTree, render

__authors__ = "Alec Springel"
__version__ = "1.0.0"
__emails__ = "aspring6@uoregon.edu"
__credits__ = "Kyra Novitzky, Seth Tal, Ronny Fuentes, Stephanie Schofield"
__date__ = "01/23/2021"


class Node(NodeMixin):
    def __init__(self, name, function, inType, outType, parent=None):
        self.name = name
        self.function = function
        self.inType = inType
        self.outType = outType
        # Parents/children are dynamically generated by checking input/output
        self.parent = parent
